# Generated by Django 3.2.7 on 2022-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(default='', max_length=100, verbose_name='User Name')),
                ('cust_m_no', models.PositiveIntegerField(default=0, max_length=10, verbose_name='Mobile no')),
                ('cust_email', models.CharField(default='', max_length=100)),
                ('cust_password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
