# Generated by Django 3.2.7 on 2022-08-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poller_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=100, verbose_name='User Name')),
                ('p_m_no', models.PositiveIntegerField(default=0, max_length=10, verbose_name='Mobile no')),
                ('p_email', models.CharField(default='', max_length=100)),
                ('p_password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='auther',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.poller_class'),
        ),
    ]
