# Generated by Django 3.2.7 on 2022-08-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_poll_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='auther',
            new_name='author',
        ),
    ]
