# Generated by Django 3.2.7 on 2022-08-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_auther_poll_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poller_Class',
            new_name='Author_Class',
        ),
    ]
