# Generated by Django 3.2.7 on 2022-08-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_poller_class_author_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='author',
        ),
    ]
